name: blue_wing_wms
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_otp_text_field: ^1.1.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/logo/sh_icon.png
  image_dark: assets/logo/sh_icon.png
  android_12:
    image: assets/logo/sh_icon.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/logo/sh_icon.png
    icon_background_color_dark: "#272727"

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/logo/
